# Generated by Django 4.0.6 on 2022-07-07 22:04

from django.db import migrations, models
import school_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_locker_student_enrollment_course_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='locker_number',
            field=models.IntegerField(unique=True, validators=[school_app.validators.is_locker_digit_valid]),
        ),
    ]
