# Generated by Django 4.0.6 on 2022-07-13 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('account_type', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('rating', models.CharField(max_length=10)),
                ('release_year', models.CharField(max_length=4)),
                ('copies_available', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_store_app.customer')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_store_app.video')),
            ],
            options={
                'unique_together': {('customer', 'video')},
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='rentals',
            field=models.ManyToManyField(through='video_store_app.Rental', to='video_store_app.video'),
        ),
    ]
