# Generated by Django 4.0.5 on 2022-07-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='favorite_color',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
